[workspace]
resolver = "2"
members = [
    "archive-client",
    "archive-engine",
    "archive-server",
    "archive-wasm"
]
default-members = [
    "archive-client",
    "archive-server",
    "archive-engine"
]

[profile.release]
lto = true
opt-level = 3